# this need to be apply first before installing certificate for any url
# =====================================================================
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
spec:
  acme:
    # You will need to fill in the proper details here.
    server: https://acme-v02.api.letsencrypt.org/directory
    email: Adminotuu@gtechglobal.online
    privateKeySecretRef:
      name: letsencrypt-prod
    solvers:
    - http01:
        ingress:
          class: n
          Nginx
